---
- name: Remove old repo
  file:
    path: "/etc/yum.repos.d/"
    state: absent
  when: ansible_distribution == "CentOS"

- name: Create repo directory
  file:
    path: "/etc/yum.repos.d/"
    state: directory
  when: ansible_distribution == "CentOS"

- block:
    - name: Change Base repo
      copy:
        remote_src: false
        src: "CentOS7-Base.repo"
        dest: "/etc/yum.repos.d/CentOS7-Base.repo"

    - name: Change epel repo
      copy:
        remote_src: false
        src: "epel7.repo"
        dest: "/etc/yum.repos.d/epel.repo"

    - name: Change epel-testing repo
      copy:
        remote_src: false
        src: "epel7-testing.repo"
        dest: "/etc/yum.repos.d/epel-testing.repo"

    - name: Insert EPEL key
      copy:
        remote_src: false
        src: "RPM-GPG-KEY-EPEL-7"
        dest: "/etc/pki/rpm-gpg"
  when: ansible_distribution == "CentOS" and  ansible_distribution_major_version|int == 7

- block:
    - name: Change Base repo
      copy:
        remote_src: false
        src: "CentOS6-Base.repo"
        dest: "/etc/yum.repos.d/CentOS6-Base.repo"

    - name: Change epel repo
      copy:
        remote_src: false
        src: "epel6.repo"
        dest: "/etc/yum.repos.d/epel.repo"

    - name: Change epel-testing repo
      copy:
        remote_src: false
        src: "epel6-testing.repo"
        dest: "/etc/yum.repos.d/epel-testing.repo"
  when: ansible_distribution == "CentOS" and  ansible_distribution_major_version|int == 6

- block:
    - name: Change Base repo
      template:
        remote_src: false
        src: "source.list.j2"
        dest: "/etc/apt/source.list"
        backup: true
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 18
