---
- name: Check if SNMP is already installed.
  stat: path=/etc/init.d/"{{ snmp_daemon }}"
  register: snmp_installed

- name: Install snmp
  apt: "name={{ item }} state=present"
  with_items:
    - "{{ snmp_packages }}"
  when: snmp_installed.stat.exists == false

- name: Start and enable snmp service
  service: "name=snmpd state=started enabled=true"
